import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import Layout from "~/components/Layout";
import Tabs from "~/components/Tabs";
import Terminal from "~/components/Terminal";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Friday</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>WELCOME PAGE</h1>
      </Layout>
    </>
  );
};

export default Home;
