import React from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import Tabs from './Tabs';

const Layout = ({ children }: { children: React.ReactNode; }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Tabs />
        {children}
      </Wrapper>
    </>
  );
};

const Wrapper = styled.main`
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;

  * {
    font-family: "FiraCodeRegular"
  }
`;

export default Layout;